name: geniopay
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  another_flushbar: ^1.10.11
  dartz: ^0.10.0
  equatable: ^2.0.0
  json_annotation: ^4.4.0
  internet_connection_checker: ^0.0.1+2
  gap: ^2.0.0
  flutter_svg: ^1.0.3

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  meta: ^1.6.0 
  build_runner: ^2.0.6
  very_good_analysis: ^2.4.0
  injectable_generator: ^1.1.2
  objectbox_generator: ^1.1.1
  json_serializable: ^6.1.3
  freezed: ^1.1.1

dependency_overrides:
  analyzer: ^4.0.0
  crypto: ^3.0.1
  http_parser: ^4.0.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  meta: ^1.7.0
  path: ^1.8.1
  xml: ^5.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
    - family: IBMPlexSans-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
    - family: IBMPlexSans-Medium
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 600

    - family: IBMPlexSans-Regular
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
